version: "3.2"

services:
  bitcoind:
    image: "samouraiwallet/dojo-bitcoind:${DOJO_BITCOIND_VERSION_TAG}"
    container_name: bitcoind
    build:
      context: ./bitcoin
    env_file:
      - ./.env
      - ./conf/docker-common.conf
      - ./conf/docker-bitcoind.conf
    restart: always
    command: "/wait-for-it.sh tor:9050 --timeout=720 --strict -- /restart.sh"
    expose:
      - "8333"
      - "28256"
      - "9501"
      - "9502"
    volumes:
      - data-bitcoind:/home/bitcoin/.bitcoin
      - data-tor:/var/lib/tor
    depends_on:
      - db
      - tor
    networks:
      dojonet:
        ipv4_address: 172.28.1.5

  node:
    depends_on:
      - bitcoind

volumes:
  data-bitcoind:
